import type { Skill } from "@/lib/types";

export const seedSkills: Skill[] = [
  {
    id: "demo-agent-skills",
    slug: "agent-skills",
    name: "Agent Skills",
    owner: "Addy Osmani",
    githubFullName: "addyosmani/agent-skills",
    description: {
      "pt-BR": "Skills de engenharia prontas para produção, criadas para agentes de programação.",
      en: "Production-grade engineering skills built for coding agents.",
    },
    repositoryUrl: "https://github.com/addyosmani/agent-skills",
    imageUrl: "https://opengraph.githubassets.com/skillder/addyosmani/agent-skills",
    installCommand: "npx skills add addyosmani/agent-skills",
    ecosystems: ["Codex", "Claude Code", "Cursor"],
    categories: ["Engenharia", "Agentes"],
    license: "MIT",
    stars: 77776,
    forks: 6120,
    likesCount: 284,
    trend24h: 428,
    updatedAt: "2026-07-12T12:00:00.000Z",
    verified: true,
    installDocumented: true,
    permissionsDeclared: true,
  },
  {
    id: "demo-superpowers",
    slug: "superpowers",
    name: "Superpowers",
    owner: "Jesse Vincent",
    githubFullName: "obra/superpowers",
    description: {
      "pt-BR": "Framework de skills e metodologia de desenvolvimento orientada por agentes.",
      en: "An agentic skills framework and software development methodology.",
    },
    repositoryUrl: "https://github.com/obra/superpowers",
    imageUrl: "https://opengraph.githubassets.com/skillder/obra/superpowers",
    installCommand: "npx skills add obra/superpowers",
    ecosystems: ["Codex", "Claude Code"],
    categories: ["Produtividade", "Engenharia"],
    license: "MIT",
    stars: 253559,
    forks: 22646,
    likesCount: 241,
    trend24h: 312,
    updatedAt: "2026-07-10T15:58:09.000Z",
    verified: true,
    installDocumented: true,
    permissionsDeclared: true,
  },
  {
    id: "demo-science-skills",
    slug: "scientific-agent-skills",
    name: "Scientific Agent Skills",
    owner: "K-Dense AI",
    githubFullName: "K-Dense-AI/scientific-agent-skills",
    description: {
      "pt-BR": "Coleção de skills científicas para pesquisa, dados biomédicos e computação.",
      en: "Scientific skills for research, biomedical data, and computation.",
    },
    repositoryUrl: "https://github.com/K-Dense-AI/scientific-agent-skills",
    imageUrl: "https://opengraph.githubassets.com/skillder/K-Dense-AI/scientific-agent-skills",
    installCommand: "npx skills add K-Dense-AI/scientific-agent-skills",
    ecosystems: ["Codex", "Claude Code", "Cursor"],
    categories: ["Pesquisa", "Dados"],
    license: "MIT",
    stars: 30815,
    forks: 3398,
    likesCount: 176,
    trend24h: 196,
    updatedAt: "2026-07-11T10:00:00.000Z",
    verified: true,
    installDocumented: true,
    permissionsDeclared: true,
  },
  {
    id: "demo-context-engineering",
    slug: "context-engineering",
    name: "Context Engineering",
    owner: "Murat Can Koylan",
    githubFullName: "muratcankoylan/Agent-Skills-for-Context-Engineering",
    description: {
      "pt-BR": "Skills para arquitetura de contexto, sistemas multiagente e aplicações de produção.",
      en: "Skills for context architecture, multi-agent systems, and production applications.",
    },
    repositoryUrl: "https://github.com/muratcankoylan/Agent-Skills-for-Context-Engineering",
    imageUrl: "https://opengraph.githubassets.com/skillder/muratcankoylan/Agent-Skills-for-Context-Engineering",
    installCommand: "npx skills add muratcankoylan/Agent-Skills-for-Context-Engineering",
    ecosystems: ["Codex", "Claude Code"],
    categories: ["Contexto", "Agentes"],
    license: "MIT",
    stars: 17099,
    forks: 2100,
    likesCount: 133,
    trend24h: 154,
    updatedAt: "2026-07-09T09:00:00.000Z",
    verified: true,
    installDocumented: true,
    permissionsDeclared: true,
  },
];
